spring:
  datasource:
    url: jdbc:mysql://www.jianbing.pro:3306/jianbing?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: ENC(akdyVo0cXjjFekVSZAc5hkqG3NsO0YIm)

  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /static/**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: false
  jackson:
    time-zone: GMT+8

server:
  port: 80
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: pro.jianbing.aboutme.entity

jasypt:
  encryptor:
    password: jianbing